require:
  - solidus_dev_support/rubocop

AllCops:
  NewCops: disable
  TargetRubyVersion: '3.0'
  Exclude:
    - sandbox/**/*
    - dummy-app/**/*
    - spec/dummy/**/*
    - vendor/bundle/**/*

# Avoiding the nested namespaces can avoid some
# ambiguities, forcing full references.
# Also saves horizontal space.
Style/ClassAndModuleChildren:
  Enabled: false

# Gain space by indenting from the start of the line,
# instead of the end of the method name.
Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

# More is more.
RSpec/MultipleExpectations:
  Enabled: false

# This was suggesting to use the dangling comma instead,
# which is super cryptic 🙈.
Style/TrailingUnderscoreVariable:
  Enabled: false

# System specs aren't describing any specific class/module.
RSpec/DescribeClass:
  Exclude:
    - spec/system/**/*

Rails/NotNullColumn:
  Exclude:
    - db/migrate/20230310152615_add_payment_method_reference_to_stripe_intents.rb

Layout/LineLength:
  Exclude:
    - db/migrate/**/*

RSpec/FilePath:
  Exclude:
    - spec/requests/solidus_stripe/webhooks_controller/**/*

Style/MultilineTernaryOperator:
  Enabled: false
